import "../styles/globals.css";
import { ChainId, ThirdwebProvider } from "@thirdweb-dev/react";
import { useState } from "react";
import NavBar from "../components/navbar";
import React from "react";
import AppContext from "../components/AppContext";
import Head from "next/head";

// This is the chainId your dApp will work on.
const activeChainId = ChainId.Mainnet;

function MyApp({ Component, pageProps }) {
  const [walletAddress, setWalletAddress] = useState(undefined);
  // console.log(walletAddress);

  return (
    <>
      <Head>
        <title>ClosedLake - Trade your NFT freely</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <AppContext.Provider
        value={{
          state: {
            walletAddress: walletAddress,
          },
          setWalletAddress: setWalletAddress,
        }}
      >
        <ThirdwebProvider desiredChainId={activeChainId}>
          <NavBar />
          {walletAddress === undefined ? (
            <h1 className="p-10 text-3xl">Please connect a wallet</h1>
          ) : (
            <Component {...pageProps} />
          )}
        </ThirdwebProvider>
      </AppContext.Provider>
    </>
  );
}

export default MyApp;
